"use client"
import { CssVarsProvider, extendTheme } from '@mui/joy'
import './globals.css'
import type { Metadata } from 'next'
import { Inter, Poppins } from 'next/font/google'

const poppins = Poppins({ subsets: ['latin'], weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const theme = extendTheme({ cssVarPrefix: 'dark' });

  return (
    <html lang="en">
      <body className={poppins.className}>
        <CssVarsProvider
          defaultMode="dark"
          theme={theme}
          colorSchemeSelector="#demo_dark-mode-by-default"
          modeStorageKey="demo_dark-mode-by-default"
          disableNestedContext
        >
          {children}
        </CssVarsProvider>
      </body>
    </html>
  )
}
